### ISSUE TITLE
Error generating feed

### ISSUE THREAD

**Issue by kjacobsen** [planetpowershell/planetpowershell#15]
From the logs:

System.Exception: Warren Frame's feed of http://ramblingcookiemonster.github.io/feed failed to load. ---> System.Xml.XmlException: Error in line 20 position 54. An error was encountered when parsing a DateTime value in the XML.
   at System.ServiceModel.Syndication.Atom10FeedFormatter.DateFromString(String dateTimeString, XmlReader reader)
   at System.ServiceModel.Syndication.Atom10FeedFormatter.TryParseItemElementFrom(XmlReader reader, SyndicationItem result)
   at System.ServiceModel.Syndication.Atom10FeedFormatter.ReadItemFrom(XmlReader reader, SyndicationItem result, Uri feedBaseUri)
   at System.ServiceModel.Syndication.Atom10FeedFormatter.ReadItem(XmlReader reader, SyndicationFeed feed)
   at System.ServiceModel.Syndication.Atom10FeedFormatter.ReadItems(XmlReader reader, SyndicationFeed feed, Boolean& areAllItemsRead)
   at System.ServiceModel.Syndication.Atom10FeedFormatter.ReadFeedFrom(XmlReader reader, SyndicationFeed result, Boolean isSourceFeed)
   at System.ServiceModel.Syndication.Atom10FeedFormatter.ReadFeed(XmlReader reader)
   at System.ServiceModel.Syndication.Atom10FeedFormatter.ReadFrom(XmlReader reader)
   at System.ServiceModel.Syndication.SyndicationFeed.Load[TSyndicationFeed](XmlReader reader)
   at BlogMonster.Infrastructure.SyndicationFeedSources.Remote.RemoteSyndicationFeedSource.Fetch()
   at BlogMonster.Cached`1.get_Value()
   at Firehose.Web.Infrastructure.CombinedFeedSource.TryLoadFeed(IAmACommunityMember tamarin, Uri uri)
   --- End of inner exception stack trace ---

**Comment by RamblingCookieMonster** [comment]
@kjacobsen - for what it's worth, I switched over to feed.xml in #17, let me know if that helped!

**Comment by kjacobsen** [comment]
Seems to have been a one of thing. Let's monitor it to see what happens.

**Comment by kjacobsen** [comment]
New Errors I am seeing:

System.InvalidOperationException
The view 'Error' or its master was not found or no view engine supports the searched locations. The following locations were searched: ~/Views/Preview/Error.aspx ~/Views/Preview/Error.ascx ~/Views/Shared/Error.aspx ~/Views/Shared/Error.ascx ~/Views/Preview/Error.cshtml ~/Views/Preview/Error.vbhtml ~/Views/Shared/Error.cshtml ~/Views/Shared/Error.vbhtml

System.InvalidOperationException: The view 'Error' or its master was not found or no view engine supports the searched locations. The following locations were searched:
~/Views/Preview/Error.aspx
~/Views/Preview/Error.ascx
~/Views/Shared/Error.aspx
~/Views/Shared/Error.ascx
~/Views/Preview/Error.cshtml
~/Views/Preview/Error.vbhtml
~/Views/Shared/Error.cshtml
~/Views/Shared/Error.vbhtml
   at System.Web.Mvc.ViewResult.FindView(ControllerContext context)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by RamblingCookieMonster** [comment]
Just starting to collect some data.  The feed URL change presumably did nothing, both point to the same data.

The error is pointing to the updated date (line 20) as far as I can tell.

`<updated>2017-01-06 02:00:00 -0500T00:00:00-00:00</updated>`

Working blogs appear to have dates like the following:

* `<pubDate>Fri, 20 Jan 2017 13:46:28 GMT</pubDate>` (Mark)
* `<lastBuildDate>Tue, 07 Feb 2017 12:13:23 +0000</lastBuildDate>` (Doug)
* `<updated>2017-02-11T17:32:43.928+01:00</updated>` (Tore)

AFAIK, I didn't mess with the theme (old version [of this](https://mmistakes.github.io/minimal-mistakes/) with some tweaks on my side).  I'll look at modifying how it generates the date, might just be a config option they expose, or might be fun with Ruby.

Cheers!

**Comment by RamblingCookieMonster** [comment]
I don't even.

Apparently someone decided [to concat some data](https://github.com/RamblingCookieMonster/RamblingCookieMonster.github.io/commit/f88333fd393e2fc1ece4a6117e11fc70d4cf739a#diff-8f1728e886ce13878bc3a0e37f5a0543L28) in the updated field, maybe with the assumption that it would simplify things.

Anything I need to do to see if this change fixes how planetpowershell reads the feed?

Cheers!

**Comment by kjacobsen** [comment]
Hi,

Thanks for taking a look. If you have made changes to your feed, then all we can do is wait and see if the error disappears from the logs. You can view the logs at http://planetpowershell.com/logs
