### ISSUE TITLE
Planet PowerShell fails to content from PoshSecurity.com

### ISSUE THREAD

**Issue by kjacobsen** [planetpowershell/planetpowershell#96]
System.Net.WebException
The request was aborted: Could not create SSL/TLS secure channel.

System.Exception: Kieran Jacobsen's feed of http://poshsecurity.com/blog/?format=rss failed to load. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Firehose.Web.Infrastructure.CombinedFeedSource.<FetchAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Firehose.Web.Infrastructure.CombinedFeedSource.<TryLoadFeedAsync>d__9.MoveNext()
   --- End of inner exception stack trace ---

**Comment by kjacobsen** [comment]
I suspect it is failing to use TLS 1.2

**Comment by kjacobsen** [comment]
I was hoping this was resolved by #97 but that doesn't appear to have worked.

**Comment by kjacobsen** [comment]
Resolved.
